/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdminFileUpload: typeof import('./src/components/admin/AdminFileUpload.vue')['default']
    CareerAutocomplete: typeof import('./src/components/autocomplete/CareerAutocomplete.vue')['default']
    ChangePassword: typeof import('./src/components/ChangePassword.vue')['default']
    ChatBot: typeof import('./src/components/ChatBot.vue')['default']
    CorrelativeNotesPanel: typeof import('./src/components/student/ratings/CorrelativeNotesPanel.vue')['default']
    CorrelativeNotesTable: typeof import('./src/components/student/ratings/CorrelativeNotesTable.vue')['default']
    DateTimePicker: typeof import('./src/components/admin/DateTimePicker.vue')['default']
    DigitalActsCard: typeof import('./src/components/teacher/digitalacts/DigitalActsCard.vue')['default']
    DigitalActsPanel: typeof import('./src/components/teacher/digitalacts/DigitalActsPanel.vue')['default']
    ExamRegisteredCard: typeof import('./src/components/student/examtables/ExamRegisteredCard.vue')['default']
    ExamRegisteredPanel: typeof import('./src/components/student/examtables/ExamRegisteredPanel.vue')['default']
    ExamTableCard: typeof import('./src/components/student/examtables/ExamTableCard.vue')['default']
    ExamTablePanel: typeof import('./src/components/student/examtables/ExamTablePanel.vue')['default']
    PercentageCircle: typeof import('./src/components/dashboard/PercentageCircle.vue')['default']
    PercentageRegistration: typeof import('./src/components/dashboard/PercentageRegistration.vue')['default']
    PerformanceAverage: typeof import('./src/components/dashboard/PerformanceAverage.vue')['default']
    PerformancePrediction: typeof import('./src/components/dashboard/PerformancePrediction.vue')['default']
    PerformanceSubjects: typeof import('./src/components/dashboard/PerformanceSubjects.vue')['default']
    PerformanceTableExam: typeof import('./src/components/dashboard/PerformanceTableExam.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StudentAutocomplete: typeof import('./src/components/autocomplete/StudentAutocomplete.vue')['default']
    StudentCardAdmin: typeof import('./src/components/admin/student/StudentCardAdmin.vue')['default']
    StudentCardLogin: typeof import('./src/components/student/StudentCardLogin.vue')['default']
    StudentNotesPanel: typeof import('./src/components/admin/student/StudentNotesPanel.vue')['default']
    StudentNotesTable: typeof import('./src/components/admin/student/StudentNotesTable.vue')['default']
    StudentRegisteredCard: typeof import('./src/components/teacher/examtables/StudentRegisteredCard.vue')['default']
    StudentRegisteredPanel: typeof import('./src/components/teacher/examtables/StudentRegisteredPanel.vue')['default']
    SubjectAutocomplete: typeof import('./src/components/autocomplete/SubjectAutocomplete.vue')['default']
    TeacherAutocomplete: typeof import('./src/components/autocomplete/TeacherAutocomplete.vue')['default']
    TeacherCardAdmin: typeof import('./src/components/admin/teacher/TeacherCardAdmin.vue')['default']
    TeacherCardLogin: typeof import('./src/components/teacher/TeacherCardLogin.vue')['default']
  }
}
