/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdminFileUpload: typeof import('./src/components/admin/AdminFileUpload.vue')['default']
    AvailableExams: typeof import('./src/components/student/AvailableExams.vue')['default']
    CareerAutocomplete: typeof import('./src/components/autocomplete/CareerAutocomplete.vue')['default']
    ChangePassword: typeof import('./src/components/student/ChangePassword.vue')['default']
    ChatBotButton: typeof import('./src/components/chatbot/ChatBotButton.vue')['default']
    ChatBotPanel: typeof import('./src/components/chatbot/ChatBotPanel.vue')['default']
    CorrelativeNotesPanel: typeof import('./src/components/student/ratings/CorrelativeNotesPanel.vue')['default']
    CorrelativeNotesTable: typeof import('./src/components/student/ratings/CorrelativeNotesTable.vue')['default']
    DateTimePicker: typeof import('./src/components/admin/DateTimePicker.vue')['default']
    EnrolledExams: typeof import('./src/components/student/EnrolledExams.vue')['default']
    ExamRegisteredCard: typeof import('./src/components/student/examtables/ExamRegisteredCard.vue')['default']
    ExamRegisteredPanel: typeof import('./src/components/student/examtables/ExamRegisteredPanel.vue')['default']
    ExamTableCard: typeof import('./src/components/student/examtables/ExamTableCard.vue')['default']
    ExamTablePanel: typeof import('./src/components/student/examtables/ExamTablePanel.vue')['default']
    ExamTableRegisteredCard: typeof import('./src/components/student/examtables/ExamRegisteredCard.vue')['default']
    FileUpload: typeof import('./src/components/admin/FileUpload.vue')['default']
    LoggedInStudentCard: typeof import('./src/components/student/StudentCardLogin.vue')['default']
    PercentageCircle: typeof import('./src/components/dashboard/PercentageCircle.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StudentAutocomplete: typeof import('./src/components/autocomplete/StudentAutocomplete.vue')['default']
    StudentCard: typeof import('./src/components/admin/student/StudentCardAdmin.vue')['default']
    StudentCardAdmin: typeof import('./src/components/admin/student/StudentCardAdmin.vue')['default']
    StudentCardLogin: typeof import('./src/components/student/StudentCardLogin.vue')['default']
    StudentGrades: typeof import('./src/components/student/StudentGrades.vue')['default']
    StudentNotesPanel: typeof import('./src/components/admin/student/StudentNotesPanel.vue')['default']
    StudentNotesTable: typeof import('./src/components/admin/student/StudentNotesTable.vue')['default']
    StudentProfile: typeof import('./src/components/student/StudentProfile.vue')['default']
    StudentRegisteredCard: typeof import('./src/components/teacher/examtables/StudentRegisteredCard.vue')['default']
    StudentRegisteredPanel: typeof import('./src/components/teacher/examtables/StudentRegisteredPanel.vue')['default']
    SubjectAutocomplete: typeof import('./src/components/autocomplete/SubjectAutocomplete.vue')['default']
    TeacherAutocomplete: typeof import('./src/components/autocomplete/TeacherAutocomplete.vue')['default']
    TeacherCardAdmin: typeof import('./src/components/admin/teacher/TeacherCardAdmin.vue')['default']
    TeacherCardLogin: typeof import('./src/components/teacher/TeacherCardLogin.vue')['default']
  }
}
