/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    'admin': RouteRecordInfo<'admin', '/admin', Record<never, never>, Record<never, never>>,
    '/admin/administration-chatbot': RouteRecordInfo<'/admin/administration-chatbot', '/admin/administration-chatbot', Record<never, never>, Record<never, never>>,
    '/admin/administration-dashboard': RouteRecordInfo<'/admin/administration-dashboard', '/admin/administration-dashboard', Record<never, never>, Record<never, never>>,
    '/admin/administration-tables': RouteRecordInfo<'/admin/administration-tables', '/admin/administration-tables', Record<never, never>, Record<never, never>>,
    '/admin/administration-upload': RouteRecordInfo<'/admin/administration-upload', '/admin/administration-upload', Record<never, never>, Record<never, never>>,
    '/admin/change-password': RouteRecordInfo<'/admin/change-password', '/admin/change-password', Record<never, never>, Record<never, never>>,
    '/admin/management-student': RouteRecordInfo<'/admin/management-student', '/admin/management-student', Record<never, never>, Record<never, never>>,
    '/admin/management-tables': RouteRecordInfo<'/admin/management-tables', '/admin/management-tables', Record<never, never>, Record<never, never>>,
    '/admin/management-teacher': RouteRecordInfo<'/admin/management-teacher', '/admin/management-teacher', Record<never, never>, Record<never, never>>,
    '/admin/student/[id]/profile': RouteRecordInfo<'/admin/student/[id]/profile', '/admin/student/:id/profile', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/admin/teacher/[id]/profile': RouteRecordInfo<'/admin/teacher/[id]/profile', '/admin/teacher/:id/profile', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/login/': RouteRecordInfo<'/login/', '/login', Record<never, never>, Record<never, never>>,
    '/student/[name]/change-password': RouteRecordInfo<'/student/[name]/change-password', '/student/:name/change-password', { name: ParamValue<true> }, { name: ParamValue<false> }>,
    'student': RouteRecordInfo<'student', '/student/:name/profile', { name: ParamValue<true> }, { name: ParamValue<false> }>,
    '/student/[name]/ratings': RouteRecordInfo<'/student/[name]/ratings', '/student/:name/ratings', { name: ParamValue<true> }, { name: ParamValue<false> }>,
    '/student/[name]/tables-exam': RouteRecordInfo<'/student/[name]/tables-exam', '/student/:name/tables-exam', { name: ParamValue<true> }, { name: ParamValue<false> }>,
    '/student/[name]/tables-registered': RouteRecordInfo<'/student/[name]/tables-registered', '/student/:name/tables-registered', { name: ParamValue<true> }, { name: ParamValue<false> }>,
    '/teacher/[name]/change-password': RouteRecordInfo<'/teacher/[name]/change-password', '/teacher/:name/change-password', { name: ParamValue<true> }, { name: ParamValue<false> }>,
    'teacher': RouteRecordInfo<'teacher', '/teacher/:name/profile', { name: ParamValue<true> }, { name: ParamValue<false> }>,
    '/teacher/[name]/students-subject': RouteRecordInfo<'/teacher/[name]/students-subject', '/teacher/:name/students-subject', { name: ParamValue<true> }, { name: ParamValue<false> }>,
    '/teacher/[name]/tables-assigned': RouteRecordInfo<'/teacher/[name]/tables-assigned', '/teacher/:name/tables-assigned', { name: ParamValue<true> }, { name: ParamValue<false> }>,
  }
}
